#!/usr/bin/env python3
"""
audio_progress.py — Generate AUDIO_PROGRESS.md tracking the NotebookLM backfill.

Reads docs/ledger.json and writes a human-readable progress report to
AUDIO_PROGRESS.md in the repository root. Intended to be run after each
daily_audio_backfill.yml run so progress is visible on GitHub.

Usage:
    python scripts/audio_progress.py
"""

import json
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR    = Path(__file__).resolve().parent.parent
LEDGER_PATH = BASE_DIR / "docs" / "ledger.json"
OUTPUT_PATH = BASE_DIR / "AUDIO_PROGRESS.md"

DAILY_QUOTA = 3   # NotebookLM free-tier audio generations per day


def _progress_bar(done: int, total: int, width: int = 40) -> str:
    filled = int(width * done / total) if total else 0
    return "█" * filled + "░" * (width - filled)


def main() -> None:
    with open(LEDGER_PATH, encoding="utf-8") as fh:
        ledger = json.load(fh)

    filings = ledger["filings"]

    # Eligible = scraped letters that could have audio (no skip_reason)
    eligible = [
        f for f in filings
        if f.get("letter_scraped") and f.get("letter_file") and not f.get("skip_reason")
    ]
    # Two-pass stable sort: ID descending first, then date ascending.
    # Same-date entries retain their ID-descending order after the second pass.
    _done = [f for f in eligible if f.get("audio_generated")]
    _done.sort(key=lambda f: f.get("id", ""), reverse=True)
    done  = sorted(_done, key=lambda f: f.get("audio_generated_date", "")[:10])
    pending = [f for f in eligible if not f.get("audio_generated")]

    total     = len(eligible)
    n_done    = len(done)
    n_pending = len(pending)
    pct       = (n_done / total * 100) if total else 0.0
    days_left = -(-n_pending // DAILY_QUOTA)   # ceiling division

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = [
        "# NotebookLM Audio Backfill — Progress Tracker",
        "",
        f"> Last updated: **{now}**  ",
        f"> Auto-generated by `daily_audio_backfill.yml` after each run.",
        "",
        "## Summary",
        "",
        "| | |",
        "|---|---|",
        f"| Letters with audio | **{n_done} / {total}** |",
        f"| Still pending | {n_pending} |",
        f"| Daily quota | ~{DAILY_QUOTA} per day (NotebookLM free tier) |",
        f"| Est. days remaining | ~{days_left} day{'s' if days_left != 1 else ''} |",
        "",
        f"`[{_progress_bar(n_done, total)}]  {pct:.1f}%`",
        "",
    ]

    # ── Completed ─────────────────────────────────────────────────────────────
    lines += [
        f"## Completed ({n_done})",
        "",
        "| # | Filing | Period | Version | Generated |",
        "|---|--------|--------|---------|-----------|",
    ]
    for i, f in enumerate(done, 1):
        gen_date = (f.get("audio_generated_date") or "")[:10] or "—"
        period   = f"{f.get('year', '')} {f.get('quarter', '')}".strip()
        version  = f.get("audio_version") or "—"
        lines.append(f"| {i} | `{f['id']}` | {period} | v{version} | {gen_date} |")

    lines.append("")

    # ── Pending ───────────────────────────────────────────────────────────────
    lines += [
        f"## Pending ({n_pending})",
        "",
        "| # | Filing | Period |",
        "|---|--------|--------|",
    ]
    for i, f in enumerate(pending, 1):
        period = f"{f.get('year', '')} {f.get('quarter', '')}".strip()
        lines.append(f"| {i} | `{f['id']}` | {period} |")

    lines += ["", "---", ""]

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"AUDIO_PROGRESS.md updated — {n_done}/{total} done "
        f"({pct:.1f}%), ~{days_left} day{'s' if days_left != 1 else ''} remaining."
    )


if __name__ == "__main__":
    main()
